### ISSUE TITLE
Navigation fails even on faithfully reproduced layout

### ISSUE THREAD

**Issue by dmitriid** [rdkcentral/solid-ui#38]
Reproduced here: https://github.com/dmitriid/lightningjs-repro (ignore `Grid.tsx`, everything is happening in `index.tsx` and `App.tsx`)

Despite seemingly copying solid-ui's storybook to a T, the focus is applied to outer elements, not to the Row and Buttons inside it, and left-right navigation throws errors:

![](https://github.com/dmitriid/lightningjs-repro/raw/master/public/assets/screenshots/focus.png)

```
dev.js:1099 Uncaught Error: Assertion failed
    at assertTruthy (assertTruthy.ts:34:11)
    at ElementNode.onRight (handleNavigation.ts:77:5)
    at propagateKeyDown (focusManager.ts:144:25)
    at handleKeyEvents (focusManager.ts:181:7)
    at focusManager.ts:231:7
    at runUpdates (dev.js:912:17)
    at runWithOwner (dev.js:578:12)
    at HTMLDocument.keyPressHandler (focusManager.ts:230:5)
```

Even though the focused element is ElementNode:

![](https://github.com/dmitriid/lightningjs-repro/raw/master/public/assets/screenshots/element-node.png)

**Comment by chiefcll** [comment]
This is due to @lightningtv/core being bundled twice in your project. I checked out your vite.config.js and its using @lightningjs rather than @lightningtv which should fix up this issue. Make sure `@lightningtv/core` is in the optimizeDeps

**Comment by dmitriid** [comment]
I feel stupid now :) I thought I re-checked everything twice.

Of course now it works. Thank you!
