### ISSUE TITLE
WebGL error on component rendition using storybook controls

### ISSUE THREAD

**Issue by ftardif** [rdkcentral/solid-ui#74]
Using the[ official solid-ui storybook](https://rdkcentral.github.io/solid-ui/?path=/story/components-button--container), changing any properties through a component control, the component should update accordingly but it creates a WebGL error: 
`WebGL: INVALID_OPERATION: bindBuffer: object does not VM1462 render-49jubT3u.js:596 belong to this context`
`WebGL: INVALID_OPERATION: uniformlf: location is not VM1462 render-49jubT3u.js:596 from the associated program`
`WebGL: INVALID_OPERATION: drawElements: no valid shader VM1462 render-49jubT3u.js:596 program in use`
``
At this refreshing the page correctly renders the component (without the webgl in the console)

See this video showing the flow creating the error, while a refresh works using the button component from the solid-ui storybook:
https://drive.google.com/file/d/1gqwKLUa7j4UdCnN20mnTKFD9JaqFM_c0/view?usp=sharing

Although the example references the solid-ui component, I have the same error with any component of the storybook we are building on our app. 

![Image](https://github.com/user-attachments/assets/38928e16-3209-4185-b931-2f7852e7a3e7)

**Comment by chiefcll** [comment]
Fixed by: https://github.com/rdkcentral/solid-ui/pull/76
